### ISSUE TITLE
Make root directory less clustered and Follow Directory Structure!

### ISSUE THREAD

**Issue by lazycipher** [technojam/technojam.github.io#11]
Make the root directory less clustered.
Follow the decided directory structure.

<img src="https://i.imgur.com/7pkDwCQ.png">

events/dex1 was supposed to be in images directory.

<img src="https://i.imgur.com/BNXVI9I.png">

**Comment by 20manas** [comment]
I'll move the events folder.
But the files directly at root need to be at root for their optimal usage.
@lazycipher
