### ISSUE TITLE
Change about.html

### ISSUE THREAD

**Issue by 20manas** [technojam/technojam.github.io#25]
1. There are a lot of grammatical and spelling mistakes.
2. The effects that have been chosen look ancient.
3. We cannot write that we were struggling to get resources on our official website, irrespective of whether or not it is true, as it tarnishes GU's reputation.
4. The page is not responsive.

@viditvarshney

**Comment by viditvarshney** [comment]
okk i will .. 
@20manas  where is grammatical error , okk i will change its look , since it good with respect to the previous look of the WEBSITE 
@20manas this all content was discussed with the heads and i personally asked what was the journey of yours.....
